require('./dist/sunchoke');
module.exports = {
    'all': 'talend.sunchoke',
    'accordion': 'talend.sunchoke.accordion',
    'badge': 'talend.sunchoke.badge',
    'datepicker': 'talend.sunchoke.date-picker',
    'dropdown': 'talend.sunchoke.dropdown',
    'dropdown-menu': 'talend.sunchoke.dropdown-menu',
	'filter-bar': 'talend.sunchoke.filter-bar',
	'filter-item-range': 'talend.sunchoke.filter-item-range',
	'filter-item-value': 'talend.sunchoke.filter-item-value',
	'filter-item': 'talend.sunchoke.filter-item',
	'filter-list': 'talend.sunchoke.filter-list',
	'filter-monitor': 'talend.sunchoke.filter-monitor',
    'horizontal-barchart': 'talend.sunchoke.horizontal-barchart',
	'list-editor': 'talend.sunchoke.list-editor',
    'quality-bar': 'talend.sunchoke.quality-bar',
    'slidable': 'talend.sunchoke.slidable',
	'splitter': 'talend.sunchoke.splitter',
	'tabs': 'talend.sunchoke.tabs',
	'vertical-barchart': 'talend.sunchoke.vertical-barchart',
    'filter-service': 'talend.sunchoke.services.filter',
};